version: 2.1
jobs:
  main:
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel=2
  pr:
    docker:
      - image: circleci/node:12.22-browsers
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel=2
workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
      - pr:
          filters:
            branches:
              ignore: main